import type { CollectionConfig } from 'payload'
import { isAdmin } from '../access/isAdmin'

export const Invoices: CollectionConfig = {
  slug: 'invoices',
  admin: {
    useAsTitle: 'invoiceNumber',
    defaultColumns: ['invoiceNumber', 'client', 'status', 'total', 'dueDate'],
    group: 'Financial',
  },
  access: {
    create: isAdmin,
    read: ({ req: { user } }) => {
      if (!user) return false
      if (['super-admin', 'sales-admin', 'ops-manager'].includes(user.role)) {
        return true
      }
      return false
    },
    update: isAdmin,
    delete: isAdmin,
  },
  fields: [
    {
      name: 'invoiceNumber',
      type: 'text',
      unique: true,
      admin: {
        description: 'Auto-generated by QuickBooks upon sync',
        readOnly: true,
      },
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'draft',
      options: [
        { label: 'Draft', value: 'draft' },
        { label: 'Pending Approval', value: 'pending-approval' },
        { label: 'Approved', value: 'approved' },
        { label: 'Sent', value: 'sent' },
        { label: 'Paid', value: 'paid' },
        { label: 'Partial Payment', value: 'partial-payment' },
        { label: 'Overdue', value: 'overdue' },
        { label: 'Void', value: 'void' },
      ],
      admin: {
        description: 'Current status of the invoice',
      },
    },
    {
      name: 'client',
      type: 'relationship',
      relationTo: 'clients',
      required: true,
      hasMany: false,
      admin: {
        description: 'Client this invoice is for',
      },
    },
    {
      name: 'jobs',
      type: 'relationship',
      relationTo: 'jobs',
      hasMany: true,
      admin: {
        description: 'Jobs included in this invoice (can be multiple)',
      },
    },
    {
      name: 'lineItems',
      type: 'array',
      label: 'Line Items',
      required: true,
      fields: [
        {
          name: 'description',
          type: 'text',
          required: true,
          admin: {
            description: 'Service description (e.g., "3D Scan - Job #123")',
          },
        },
        {
          name: 'quantity',
          type: 'number',
          required: true,
          defaultValue: 1,
          min: 0,
        },
        {
          name: 'rate',
          type: 'number',
          required: true,
          min: 0,
          admin: {
            description: 'Price per unit',
          },
        },
        {
          name: 'amount',
          type: 'number',
          required: true,
          min: 0,
          admin: {
            description: 'Total amount (quantity × rate)',
            readOnly: true,
          },
        },
        {
          name: 'taxable',
          type: 'checkbox',
          defaultValue: true,
          admin: {
            description: 'Whether this line item is subject to tax',
          },
        },
        {
          name: 'jobReference',
          type: 'text',
          admin: {
            description: 'Reference to job ID/number for this line item',
          },
        },
      ],
    },
    {
      name: 'subtotal',
      type: 'number',
      required: true,
      defaultValue: 0,
      admin: {
        description: 'Sum of all line items before tax',
        readOnly: true,
      },
    },
    {
      name: 'taxRate',
      type: 'number',
      defaultValue: 0,
      admin: {
        description: 'Tax rate percentage (e.g., 8.25 for 8.25%)',
        readOnly: true,
      },
    },
    {
      name: 'taxAmount',
      type: 'number',
      defaultValue: 0,
      admin: {
        description: 'Calculated tax amount',
        readOnly: true,
      },
    },
    {
      name: 'total',
      type: 'number',
      required: true,
      defaultValue: 0,
      admin: {
        description: 'Total amount including tax',
        readOnly: true,
      },
    },
    {
      name: 'invoiceDate',
      type: 'date',
      required: true,
      defaultValue: () => new Date().toISOString(),
      admin: {
        description: 'Date the invoice was created',
        date: {
          pickerAppearance: 'dayOnly',
        },
      },
    },
    {
      name: 'dueDate',
      type: 'date',
      required: true,
      admin: {
        description: 'Payment due date',
        date: {
          pickerAppearance: 'dayOnly',
        },
      },
    },
    {
      name: 'paidDate',
      type: 'date',
      admin: {
        description: 'Date the invoice was fully paid',
        date: {
          pickerAppearance: 'dayOnly',
        },
      },
    },
    {
      name: 'paidAmount',
      type: 'number',
      defaultValue: 0,
      min: 0,
      admin: {
        description: 'Amount paid (for partial payments)',
      },
    },
    {
      name: 'terms',
      type: 'select',
      options: [
        { label: 'Due on Receipt', value: 'due-on-receipt' },
        { label: 'Net 15', value: 'net-15' },
        { label: 'Net 30', value: 'net-30' },
        { label: 'Net 45', value: 'net-45' },
        { label: 'Net 60', value: 'net-60' },
      ],
      defaultValue: 'net-30',
      admin: {
        description: 'Payment terms (copied from client preferences)',
      },
    },
    {
      name: 'notes',
      type: 'textarea',
      admin: {
        description: 'Customer-facing notes (appears on invoice)',
      },
    },
    {
      name: 'internalNotes',
      type: 'textarea',
      admin: {
        description: 'Internal notes (not visible to customer)',
      },
    },
    {
      name: 'quickbooks',
      type: 'group',
      label: 'QuickBooks Sync',
      fields: [
        {
          name: 'invoiceId',
          type: 'text',
          admin: {
            description: 'QuickBooks Invoice ID',
            readOnly: true,
          },
        },
        {
          name: 'syncStatus',
          type: 'select',
          defaultValue: 'not-synced',
          options: [
            { label: 'Not Synced', value: 'not-synced' },
            { label: 'Synced', value: 'synced' },
            { label: 'Error', value: 'error' },
          ],
          admin: {
            readOnly: true,
          },
        },
        {
          name: 'lastSyncedAt',
          type: 'date',
          admin: {
            description: 'Last successful sync timestamp',
            readOnly: true,
          },
        },
        {
          name: 'syncError',
          type: 'textarea',
          admin: {
            description: 'Error message if sync failed',
            readOnly: true,
          },
        },
      ],
    },
    {
      name: 'approvedBy',
      type: 'relationship',
      relationTo: 'users',
      hasMany: false,
      admin: {
        description: 'User who approved this invoice',
        readOnly: true,
      },
    },
    {
      name: 'approvedAt',
      type: 'date',
      admin: {
        description: 'When the invoice was approved',
        readOnly: true,
      },
    },
    {
      name: 'createdBy',
      type: 'relationship',
      relationTo: 'users',
      hasMany: false,
      admin: {
        description: 'User who created this invoice',
      },
    },
  ],
  timestamps: true,
}
