export const defaultWorkflowTemplates = [
  {
    name: 'Outsourced - Scan Only',
    jobType: 'outsourced-scan-only',
    isActive: true,
    description: 'Standard workflow for outsourced jobs where we scan and upload to client account',
    steps: [
      {
        name: 'Job Request',
        description: 'Job created, awaiting scheduling',
        order: 1,
        statusMapping: 'request',
        requiredRole: 'ops-manager',
        actionLabel: 'Ready',
        requiresDeliverables: false,
        triggers: {
          sendNotification: true,
          notificationRecipients: ['ops-manager'],
          notificationMessage: 'New job request {{jobId}} - {{modelName}} needs scheduling',
          sendClientEmail: false,
          createInvoice: false,
          createRecurringInvoice: false,
        },
      },
      {
        name: 'Job Scheduled',
        description: 'Tech assigned, date/time confirmed',
        order: 2,
        statusMapping: 'scheduled',
        requiredRole: 'ops-manager',
        actionLabel: 'Send to Tech',
        requiresDeliverables: false,
        triggers: {
          sendNotification: true,
          notificationRecipients: ['tech'],
          notificationMessage: 'New job assigned for {{targetDate}}',
          sendClientEmail: false,
          createInvoice: false,
          createRecurringInvoice: false,
        },
      },
      {
        name: 'Scanned',
        description: 'Tech has completed the on-site scan',
        order: 3,
        statusMapping: 'scanned',
        requiredRole: 'tech',
        actionLabel: 'Scan Complete',
        requiresDeliverables: false,
        triggers: {
          sendNotification: true,
          notificationRecipients: ['ops-manager'],
          notificationMessage: 'Scan completed for {{jobId}}',
          sendClientEmail: false,
          createInvoice: false,
          createRecurringInvoice: false,
        },
      },
      {
        name: 'Scan Uploaded',
        description: 'Model has been uploaded to client account',
        order: 4,
        statusMapping: 'scanned',
        requiredRole: 'tech',
        actionLabel: 'Scan Uploaded',
        requiresDeliverables: false,
        triggers: {
          sendNotification: true,
          notificationRecipients: ['post-production'],
          notificationMessage: 'Scan uploaded for {{modelName}}',
          sendClientEmail: false,
          createInvoice: false,
          createRecurringInvoice: false,
        },
      },
      {
        name: 'Post-Production',
        description: 'Post-production QC and deliverable URL confirmation',
        order: 5,
        statusMapping: 'qc',
        requiredRole: 'post-producer',
        actionLabel: 'Complete Step',
        requiresDeliverables: true,
        triggers: {
          sendNotification: false,
          sendClientEmail: false,
          createInvoice: false,
          createRecurringInvoice: false,
        },
      },
      {
        name: 'Sent to Client',
        description: 'Deliverables sent to client',
        order: 6,
        statusMapping: 'done',
        requiredRole: 'post-producer',
        actionLabel: 'Send to Client',
        requiresDeliverables: true,
        triggers: {
          sendNotification: true,
          notificationRecipients: ['sales-admin'],
          notificationMessage: '{{jobId}} - {{modelName}} delivered to client. Ready for invoicing.',
          sendClientEmail: true,
          emailTemplate: 'job-complete',
          createInvoice: false,
          createRecurringInvoice: false,
        },
      },
      {
        name: 'Complete & Invoice',
        description: 'Job complete, invoice created',
        order: 7,
        statusMapping: 'done',
        requiredRole: 'sales-admin',
        actionLabel: 'Send Invoice',
        requiresDeliverables: false,
        triggers: {
          sendNotification: false,
          sendClientEmail: false,
          createInvoice: true,
          createRecurringInvoice: false,
        },
      },
    ],
  },
  {
    name: 'Direct - Scan + Hosting',
    jobType: 'direct-scan-hosted',
    isActive: true,
    description: 'Direct customer job with scan hosted by us (includes yearly hosting after first year)',
    steps: [
      {
        name: 'Job Request',
        description: 'Job created, awaiting scheduling',
        order: 1,
        statusMapping: 'request',
        requiredRole: 'ops-manager',
        actionLabel: 'Ready',
        requiresDeliverables: false,
        triggers: {
          sendNotification: true,
          notificationRecipients: ['ops-manager'],
          notificationMessage: 'New job request {{jobId}} - {{modelName}} needs scheduling',
          sendClientEmail: false,
          createInvoice: false,
          createRecurringInvoice: false,
        },
      },
      {
        name: 'Job Scheduled',
        description: 'Tech assigned, date/time confirmed',
        order: 2,
        statusMapping: 'scheduled',
        requiredRole: 'ops-manager',
        actionLabel: 'Send to Tech',
        requiresDeliverables: false,
        triggers: {
          sendNotification: true,
          notificationRecipients: ['tech'],
          notificationMessage: 'New job assigned for {{targetDate}}',
          sendClientEmail: false,
          createInvoice: false,
          createRecurringInvoice: false,
        },
      },
      {
        name: 'Scanned',
        description: 'Tech has completed the on-site scan',
        order: 3,
        statusMapping: 'scanned',
        requiredRole: 'tech',
        actionLabel: 'Scan Complete',
        requiresDeliverables: false,
        triggers: {
          sendNotification: true,
          notificationRecipients: ['ops-manager'],
          notificationMessage: 'Scan completed for {{jobId}}',
          sendClientEmail: false,
          createInvoice: false,
          createRecurringInvoice: false,
        },
      },
      {
        name: 'Scan Uploaded',
        description: 'Model has been uploaded to our hosting account',
        order: 4,
        statusMapping: 'scanned',
        requiredRole: 'tech',
        actionLabel: 'Scan Uploaded',
        requiresDeliverables: false,
        triggers: {
          sendNotification: true,
          notificationRecipients: ['post-production'],
          notificationMessage: 'Scan uploaded for {{modelName}}',
          sendClientEmail: false,
          createInvoice: false,
          createRecurringInvoice: false,
        },
      },
      {
        name: 'Post-Production',
        description: 'Post-production QC and deliverable URL confirmation',
        order: 5,
        statusMapping: 'qc',
        requiredRole: 'post-producer',
        actionLabel: 'Complete Step',
        requiresDeliverables: true,
        triggers: {
          sendNotification: false,
          sendClientEmail: false,
          createInvoice: false,
          createRecurringInvoice: false,
        },
      },
      {
        name: 'Sent to Client',
        description: 'Deliverables sent to client',
        order: 6,
        statusMapping: 'done',
        requiredRole: 'post-producer',
        actionLabel: 'Send to Client',
        requiresDeliverables: true,
        triggers: {
          sendNotification: true,
          notificationRecipients: ['sales-admin'],
          notificationMessage: '{{jobId}} - {{modelName}} delivered to client. Ready for invoicing.',
          sendClientEmail: true,
          emailTemplate: 'job-complete',
          createInvoice: false,
          createRecurringInvoice: false,
        },
      },
      {
        name: 'Complete & Invoice',
        description: 'Job complete, invoice created, recurring hosting invoice scheduled',
        order: 7,
        statusMapping: 'done',
        requiredRole: 'sales-admin',
        actionLabel: 'Send Invoice',
        requiresDeliverables: false,
        triggers: {
          sendNotification: false,
          sendClientEmail: false,
          createInvoice: true,
          createRecurringInvoice: true,
          recurringInvoiceDelay: 365,
          recurringInvoiceAmount: 50,
        },
      },
    ],
  },
  {
    name: 'Direct - Scan + Floor Plan',
    jobType: 'direct-scan-floorplan',
    isActive: true,
    description: 'Direct customer job with scan and floor plan drafting',
    steps: [
      {
        name: 'Job Request',
        description: 'Job created, awaiting scheduling',
        order: 1,
        statusMapping: 'request',
        requiredRole: 'ops-manager',
        actionLabel: 'Ready',
        requiresDeliverables: false,
        triggers: {
          sendNotification: true,
          notificationRecipients: ['ops-manager'],
          notificationMessage: 'New job request {{jobId}} - {{modelName}} needs scheduling',
          sendClientEmail: false,
          createInvoice: false,
          createRecurringInvoice: false,
        },
      },
      {
        name: 'Job Scheduled',
        description: 'Tech assigned, date/time confirmed',
        order: 2,
        statusMapping: 'scheduled',
        requiredRole: 'ops-manager',
        actionLabel: 'Send to Tech',
        requiresDeliverables: false,
        triggers: {
          sendNotification: true,
          notificationRecipients: ['tech'],
          notificationMessage: 'New job assigned for {{targetDate}}',
          sendClientEmail: false,
          createInvoice: false,
          createRecurringInvoice: false,
        },
      },
      {
        name: 'Scanned',
        description: 'Tech has completed the on-site scan',
        order: 3,
        statusMapping: 'scanned',
        requiredRole: 'tech',
        actionLabel: 'Scan Complete',
        requiresDeliverables: false,
        triggers: {
          sendNotification: true,
          notificationRecipients: ['ops-manager'],
          notificationMessage: 'Scan completed for {{jobId}}',
          sendClientEmail: false,
          createInvoice: false,
          createRecurringInvoice: false,
        },
      },
      {
        name: 'Scan Uploaded',
        description: 'Model has been uploaded',
        order: 4,
        statusMapping: 'scanned',
        requiredRole: 'tech',
        actionLabel: 'Scan Uploaded',
        requiresDeliverables: false,
        triggers: {
          sendNotification: true,
          notificationRecipients: ['post-production'],
          notificationMessage: 'Scan uploaded for {{modelName}}. Floor plan drafting can begin.',
          sendClientEmail: false,
          createInvoice: false,
          createRecurringInvoice: false,
        },
      },
      {
        name: 'Floor Plan Drafting',
        description: 'External vendor creating floor plans',
        order: 5,
        statusMapping: 'qc',
        requiredRole: 'post-producer',
        actionLabel: 'Floor Plans Received',
        requiresDeliverables: false,
        triggers: {
          sendNotification: true,
          notificationRecipients: ['post-production'],
          notificationMessage: 'Floor plans received for {{jobId}}. Ready for integration.',
          sendClientEmail: false,
          createInvoice: false,
          createRecurringInvoice: false,
        },
      },
      {
        name: 'Post-Production',
        description: 'Integrate floor plans, QC, and finalize deliverables',
        order: 6,
        statusMapping: 'qc',
        requiredRole: 'post-producer',
        actionLabel: 'Complete Step',
        requiresDeliverables: true,
        triggers: {
          sendNotification: false,
          sendClientEmail: false,
          createInvoice: false,
          createRecurringInvoice: false,
        },
      },
      {
        name: 'Sent to Client',
        description: 'Deliverables sent to client',
        order: 7,
        statusMapping: 'done',
        requiredRole: 'post-producer',
        actionLabel: 'Send to Client',
        requiresDeliverables: true,
        triggers: {
          sendNotification: true,
          notificationRecipients: ['sales-admin'],
          notificationMessage: '{{jobId}} - {{modelName}} delivered to client. Ready for invoicing.',
          sendClientEmail: true,
          emailTemplate: 'job-complete',
          createInvoice: false,
          createRecurringInvoice: false,
        },
      },
      {
        name: 'Complete & Invoice',
        description: 'Job complete, invoice created',
        order: 8,
        statusMapping: 'done',
        requiredRole: 'sales-admin',
        actionLabel: 'Send Invoice',
        requiresDeliverables: false,
        triggers: {
          sendNotification: false,
          sendClientEmail: false,
          createInvoice: true,
          createRecurringInvoice: false,
        },
      },
    ],
  },
]
