/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    comments: Comment;
    clients: Client;
    technicians: Technician;
    vendors: Vendor;
    products: Product;
    equipment: Equipment;
    jobs: Job;
    invoices: Invoice;
    payments: Payment;
    notifications: Notification;
    'notification-templates': NotificationTemplate;
    'workflow-templates': WorkflowTemplate;
    'job-templates': JobTemplate;
    'job-messages': JobMessage;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    technicians: TechniciansSelect<false> | TechniciansSelect<true>;
    vendors: VendorsSelect<false> | VendorsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    equipment: EquipmentSelect<false> | EquipmentSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'notification-templates': NotificationTemplatesSelect<false> | NotificationTemplatesSelect<true>;
    'workflow-templates': WorkflowTemplatesSelect<false> | WorkflowTemplatesSelect<true>;
    'job-templates': JobTemplatesSelect<false> | JobTemplatesSelect<true>;
    'job-messages': JobMessagesSelect<false> | JobMessagesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'super-admin' | 'sales-admin' | 'ops-manager' | 'tech' | 'client-partner' | 'post-producer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Comments submitted by visitors on blog posts
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  content: string;
  author: {
    name: string;
    email: string;
  };
  post: number | Post;
  /**
   * Comments must be approved before they appear publicly
   */
  isApproved?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  /**
   * Name of the person who receives communications at this company
   */
  primaryContact?: string | null;
  clientType: 'retail' | 'outsourcing-partner';
  billingPreference: 'immediate' | 'weekly-batch' | 'monthly-batch' | 'payment-first';
  email?: string | null;
  phone?: string | null;
  companyName?: string | null;
  billingAddress?: string | null;
  notes?: string | null;
  /**
   * Client-specific instructions that will auto-populate in the "General Instructions for Tech" field when this client is selected for a job. Use for recurring client requirements (e.g., "Always call POC 30 min before arrival").
   */
  instructionTemplate?: string | null;
  /**
   * User responsible for managing this client relationship
   */
  accountManager?: (number | null) | User;
  /**
   * Default workflow template that will be assigned to new jobs for this client. Can be overridden per job.
   */
  defaultWorkflow?: (number | null) | WorkflowTemplate;
  invoicingPreferences?: {
    /**
     * Default payment terms for invoices
     */
    terms?: ('due-on-receipt' | 'net-15' | 'net-30' | 'net-45' | 'net-60') | null;
    /**
     * For weekly batch: 1=Monday, 7=Sunday. For monthly batch: day of month (1-31)
     */
    batchDay?: number | null;
    /**
     * Notes that will appear on all invoices for this client
     */
    invoiceNotes?: string | null;
    /**
     * Skip manual approval and automatically create draft invoices in QuickBooks
     */
    autoApprove?: boolean | null;
    /**
     * Client is exempt from sales tax
     */
    taxExempt?: boolean | null;
    /**
     * Sales tax percentage based on client location (e.g., 8.25 for 8.25%)
     */
    taxRate?: number | null;
    /**
     * Location determining tax rate
     */
    taxJurisdiction?: string | null;
  };
  integrations?: {
    quickbooks?: {
      /**
       * Auto-populated when synced with QuickBooks
       */
      customerId?: string | null;
      syncStatus?: ('not-synced' | 'synced' | 'error' | 'pending') | null;
      lastSyncedAt?: string | null;
      syncError?: string | null;
    };
    hubspot?: {
      /**
       * Auto-populated when synced with HubSpot
       */
      contactId?: string | null;
      syncStatus?: ('not-synced' | 'synced' | 'error' | 'pending') | null;
      lastSyncedAt?: string | null;
      syncError?: string | null;
    };
  };
  notificationPreferences?: {
    /**
     * Send automatic notifications to client when job status changes
     */
    enableNotifications?: boolean | null;
    /**
     * Email address for job notifications (defaults to main email if empty)
     */
    notificationEmail?: string | null;
    /**
     * Phone number for SMS notifications (optional)
     */
    notificationPhone?: string | null;
    notifyOnScheduled?: boolean | null;
    notifyOnCompleted?: boolean | null;
    notifyOnDelivered?: boolean | null;
    notifyOnScanCompleted?: boolean | null;
    notifyOnUploadCompleted?: boolean | null;
    notifyOnQcCompleted?: boolean | null;
    notifyOnTransferCompleted?: boolean | null;
    notifyOnFloorplanCompleted?: boolean | null;
    notifyOnPhotosCompleted?: boolean | null;
    notifyOnAsbuiltsCompleted?: boolean | null;
    /**
     * Optional custom message to include in all notifications to this client
     */
    customMessage?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-templates".
 */
export interface WorkflowTemplate {
  id: number;
  /**
   * e.g., "Outsourced Scan Only", "Direct Scan + Hosting"
   */
  name: string;
  /**
   * Type of job this workflow applies to
   */
  jobType: 'outsourced-scan-only' | 'direct-scan-hosted' | 'direct-scan-floorplan' | 'custom';
  /**
   * Only active templates can be assigned to new jobs
   */
  isActive?: boolean | null;
  /**
   * Brief description of this workflow
   */
  description?: string | null;
  /**
   * Define the workflow steps in order
   */
  steps: {
    /**
     * e.g., "Scan Complete", "Upload to Client Account"
     */
    name: string;
    /**
     * What needs to be done in this step
     */
    description?: string | null;
    /**
     * Order of this step (1, 2, 3...)
     */
    order: number;
    /**
     * What job status this step represents
     */
    statusMapping: 'request' | 'scheduled' | 'scanned' | 'qc' | 'done' | 'archived';
    /**
     * Which role can mark this step as complete
     */
    requiredRole?: ('tech' | 'post-producer' | 'qc' | 'ops-manager' | 'sales-admin' | 'admin') | null;
    /**
     * Text for the action button (e.g., "Mark Scan Complete")
     */
    actionLabel?: string | null;
    /**
     * Does this step require adding deliverable URLs?
     */
    requiresDeliverables?: boolean | null;
    /**
     * What happens automatically when this step is completed
     */
    triggers?: {
      sendNotification?: boolean | null;
      notificationRecipients?: ('tech' | 'post-production' | 'qc' | 'ops-manager' | 'sales')[] | null;
      /**
       * Use {{jobId}}, {{modelName}}, {{clientName}} as placeholders
       */
      notificationMessage?: string | null;
      /**
       * Send email to client when this step completes
       */
      sendClientEmail?: boolean | null;
      emailTemplate?: ('job-complete' | 'qc-approved' | 'custom') | null;
      /**
       * Automatically create invoice when this step completes
       */
      createInvoice?: boolean | null;
      /**
       * Create recurring invoice (e.g., yearly hosting)
       */
      createRecurringInvoice?: boolean | null;
      /**
       * Days after step completion to create recurring invoice (e.g., 365 for 1 year)
       */
      recurringInvoiceDelay?: number | null;
      /**
       * Amount for recurring invoice (e.g., 50 for $50 hosting)
       */
      recurringInvoiceAmount?: number | null;
    };
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technicians".
 */
export interface Technician {
  id: number;
  name: string;
  email: string;
  /**
   * Link this technician to a user account for portal access
   */
  user?: (number | null) | User;
  type: 'commission' | 'w2' | 'partner';
  /**
   * For outsourced partners: the vendor company they work for
   */
  vendor?: (number | null) | Vendor;
  baseCommissionRate?: number | null;
  phone?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Subcontractor vendor companies for outsourced work
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors".
 */
export interface Vendor {
  id: number;
  companyName: string;
  contactPerson?: string | null;
  billingEmail: string;
  billingPhone?: string | null;
  taxID?: string | null;
  paymentTerms?: string | null;
  notes?: string | null;
  active?: boolean | null;
  integrations?: {
    quickbooks?: {
      /**
       * The vendor ID from QuickBooks for API queries
       */
      vendorId?: string | null;
      syncStatus?: ('not-synced' | 'synced' | 'error') | null;
      lastSyncedAt?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  category: 'capture-service' | 'documentation-product' | 'logistics-fee';
  unitType: 'flat' | 'per-sq-ft' | 'per-hour' | 'per-day' | 'per-item';
  basePrice: number;
  isRecurring?: boolean | null;
  requiresVendor?: boolean | null;
  description?: string | null;
  /**
   * Default instructions that will auto-populate when this product is added to a job. Can be customized per-job.
   */
  defaultInstructions?: string | null;
  /**
   * Whether this product is subject to sales tax
   */
  taxable?: boolean | null;
  /**
   * Automatically add an external expense when this product is added to a job (e.g., floor plans, photo editing)
   */
  hasDefaultExpense?: boolean | null;
  /**
   * Default cost for the auto-generated expense (can be edited per job)
   */
  defaultExpenseCost?: number | null;
  /**
   * Description for the auto-generated expense
   */
  expenseDescription?: string | null;
  /**
   * Hide this product from technician calendar invites by default (e.g., for post-production tasks like floor plans, QC, hosting). Can be overridden per-job.
   */
  excludeFromCalendar?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment".
 */
export interface Equipment {
  id: number;
  label: string;
  assetId: string;
  type: 'camera' | 'drone' | 'lidar' | 'other';
  lastCalibrationDate?: string | null;
  nextMaintenanceDue?: string | null;
  assignedTo?: (number | null) | Technician;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  /**
   * Unique job identifier. Can be manually set for outsourcing partners who use their own IDs.
   */
  jobId?: string | null;
  modelName: string;
  priority?: ('low' | 'normal' | 'high' | 'rush') | null;
  status: 'request' | 'scheduled' | 'scanned' | 'qc' | 'done' | 'archived';
  /**
   * Track invoicing status of completed jobs
   */
  invoiceStatus?: ('not-invoiced' | 'ready' | 'invoiced' | 'paid') | null;
  /**
   * Invoice this job is included in
   */
  invoice?: (number | null) | Invoice;
  /**
   * Date this job was invoiced
   */
  invoicedAt?: string | null;
  /**
   * For outsourced jobs, this is the partner (e.g., Matterport). For direct jobs, this is the actual client.
   */
  client: number | Client;
  /**
   * The actual end client when job is outsourced (e.g., "Spencer Technologies (4)")
   */
  endClientName?: string | null;
  /**
   * Company name only, for filtering and reporting
   */
  endClientCompany?: string | null;
  tech?: (number | null) | Technician;
  sitePOCName?: string | null;
  sitePOCPhone?: string | null;
  sitePOCEmail?: string | null;
  captureAddress?: string | null;
  city?: string | null;
  state?: string | null;
  zip?: string | null;
  sqFt?: number | null;
  /**
   * Estimated time to complete this job. Auto-calculated from square footage (30 min per 1000 sqft) or manually entered.
   */
  estimatedDuration?: number | null;
  propertyType?: ('commercial' | 'residential' | 'industrial' | 'other') | null;
  schedulingNotes?: string | null;
  /**
   * Geographic region for calendar color-coding
   */
  region?: ('austin' | 'san-antonio' | 'outsourced' | 'other') | null;
  captureType?: ('matterport' | 'lidar' | 'drone' | 'other') | null;
  equipment?: (number | null) | Equipment;
  purposeOfScan?: string | null;
  /**
   * Overall instructions/notes for the technician assigned to this job
   */
  techInstructions?: string | null;
  lineItems?:
    | {
        product: number | Product;
        quantity: number;
        /**
         * Detailed instructions for completing this specific item
         */
        instructions?: string | null;
        /**
         * Hide this item from the technician's calendar invite to-do list (e.g., for post-production only tasks)
         */
        excludeFromCalendar?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Add custom to-do items that are not products (e.g., specific tasks, reminders)
   */
  customTodoItems?:
    | {
        task: string;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  targetDate?: string | null;
  /**
   * Timezone for the job location
   */
  timezone?:
    | ('America/Chicago' | 'America/New_York' | 'America/Denver' | 'America/Los_Angeles' | 'America/Phoenix')
    | null;
  scannedDate?: string | null;
  /**
   * Google Calendar event ID for updating existing events
   */
  googleCalendarEventId?: string | null;
  /**
   * Where to upload the main project files (e.g., Matterport scans)
   */
  uploadLink?: string | null;
  /**
   * Where to upload additional media (photos, videos, etc.)
   */
  mediaUploadLink?: string | null;
  gasExpense?: number | null;
  isOutsourced?: boolean | null;
  vendorPrice?: number | null;
  travelPayout?: number | null;
  offHoursPayout?: number | null;
  commissionPayoutDate?: string | null;
  commissionPaymentStatus?: ('pending' | 'paid') | null;
  commissionPaidAt?: string | null;
  /**
   * The workflow template that defines steps and automation for this job
   */
  workflowTemplate?: (number | null) | WorkflowTemplate;
  /**
   * Track completion of workflow steps
   */
  workflowSteps?:
    | {
        stepName: string;
        completed?: boolean | null;
        completedAt?: string | null;
        completedBy?: string | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  qcChecklist?: {
    accuracyOk?: boolean | null;
    coverageOk?: boolean | null;
    fileNamingOk?: boolean | null;
  };
  qcStatus?: ('pending' | 'in-review' | 'passed' | 'needs-revision' | 'rejected') | null;
  /**
   * Post-producer assigned to review this job
   */
  qcAssignedTo?: (number | null) | User;
  /**
   * Notes from QC review process
   */
  qcNotes?: string | null;
  /**
   * When QC review started
   */
  qcStartTime?: string | null;
  /**
   * When QC review was completed
   */
  qcEndTime?: string | null;
  /**
   * Track revision requests during QC
   */
  revisionRequests?:
    | {
        requestedBy?: string | null;
        requestedAt?: string | null;
        description: string;
        resolved?: boolean | null;
        resolvedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  totalPrice?: number | null;
  vendorCost?: number | null;
  margin?: number | null;
  /**
   * Track costs for floor plans, as-builts, photo editing, etc.
   */
  externalExpenses?:
    | {
        description: string;
        supplier?: string | null;
        contactInfo?: string | null;
        amount: number;
        paymentStatus?: ('unpaid' | 'paid' | 'pending') | null;
        paidDate?: string | null;
        notes?: string | null;
        /**
         * Indicates this expense was automatically created based on product settings
         */
        autoGenerated?: boolean | null;
        /**
         * ID of the corresponding bill in QuickBooks
         */
        quickbooksId?: string | null;
        /**
         * Document number of the bill in QuickBooks
         */
        quickbooksDocNumber?: string | null;
        /**
         * When this expense was last synced with QuickBooks
         */
        quickbooksSyncedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-populated when outsourced tech is assigned, or manually set
   */
  subcontractorVendor?: (number | null) | Vendor;
  /**
   * PDF or CSV invoice from subcontractor
   */
  subcontractorInvoiceAttachment?: (number | null) | Media;
  /**
   * Parsed or manually entered invoice details
   */
  subInvoiceData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Indicates invoice has been imported to QuickBooks and added to expenses
   */
  subInvoiceImported?: boolean | null;
  discount?: {
    type?: ('none' | 'fixed' | 'percentage') | null;
    /**
     * Enter dollar amount for fixed or percentage for percentage discount
     */
    value?: number | null;
    /**
     * Automatically calculated discount in dollars
     */
    amount?: number | null;
  };
  /**
   * Auto-calculated from line items
   */
  subtotal?: number | null;
  /**
   * Auto-calculated based on client tax rate and taxable products
   */
  taxAmount?: number | null;
  /**
   * Subtotal + Tax - Discount
   */
  totalWithTax?: number | null;
  /**
   * Unique token for tech portal access
   */
  completionToken?: string | null;
  /**
   * Links to final deliverables for client access
   */
  deliverables?: {
    /**
     * Link to the 3D model (e.g., Matterport, CloudPano)
     */
    model3dLink?: string | null;
    /**
     * Link or zip file URL for floor plans
     */
    floorPlansLink?: string | null;
    /**
     * Link or zip file URL for photos and videos
     */
    photosVideosLink?: string | null;
    /**
     * Link or zip file URL for as-built documentation
     */
    asBuiltsLink?: string | null;
    /**
     * Link for any additional deliverables
     */
    otherAssetsLink?: string | null;
    /**
     * Internal notes about the deliverables
     */
    deliveryNotes?: string | null;
    /**
     * When the deliverables were provided to the client
     */
    deliveredDate?: string | null;
  };
  /**
   * Secure token for subcontractor message access
   */
  messageToken?: string | null;
  /**
   * Scheduling request sent to technician
   */
  schedulingRequest?: {
    requestType?: ('time-windows' | 'specific-time' | 'tech-proposes') | null;
    sentAt?: string | null;
    /**
     * When the tech must respond by (typically 24 hours)
     */
    deadline?: string | null;
    reminderSent?: boolean | null;
    reminderSentAt?: string | null;
    /**
     * For time-windows and specific-time request types
     */
    timeOptions?:
      | {
          optionNumber: number;
          date: string;
          timeWindow?: ('morning' | 'afternoon' | 'evening' | 'custom') | null;
          /**
           * e.g., 9:00am
           */
          startTime?: string | null;
          /**
           * e.g., 12:00pm
           */
          endTime?: string | null;
          /**
           * For specific-time requests (e.g., 2:00pm)
           */
          specificTime?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * For tech-proposes request type
     */
    requestMessage?: string | null;
    specialInstructions?: string | null;
  };
  /**
   * Technician response to scheduling request
   */
  techResponse?: {
    respondedAt?: string | null;
    interested?: boolean | null;
    /**
     * Which option number the tech selected
     */
    selectedOption?: number | null;
    /**
     * Tech's preferred start time within the selected window
     */
    preferredStartTime?: string | null;
    /**
     * For tech-proposes request type
     */
    proposedOptions?:
      | {
          date: string;
          startTime: string;
          notes?: string | null;
          id?: string | null;
        }[]
      | null;
    declineReason?: string | null;
    notes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  /**
   * Auto-generated by QuickBooks upon sync
   */
  invoiceNumber?: string | null;
  /**
   * Current status of the invoice
   */
  status: 'draft' | 'pending-approval' | 'approved' | 'sent' | 'paid' | 'partial-payment' | 'overdue' | 'void';
  /**
   * Client this invoice is for
   */
  client: number | Client;
  /**
   * Jobs included in this invoice (can be multiple)
   */
  jobs?: (number | Job)[] | null;
  lineItems: {
    /**
     * Service description (e.g., "3D Scan - Job #123")
     */
    description: string;
    quantity: number;
    /**
     * Price per unit
     */
    rate: number;
    /**
     * Total amount (quantity × rate)
     */
    amount: number;
    /**
     * Whether this line item is subject to tax
     */
    taxable?: boolean | null;
    /**
     * Reference to job ID/number for this line item
     */
    jobReference?: string | null;
    id?: string | null;
  }[];
  /**
   * Sum of all line items before tax
   */
  subtotal: number;
  /**
   * Tax rate percentage (e.g., 8.25 for 8.25%)
   */
  taxRate?: number | null;
  /**
   * Calculated tax amount
   */
  taxAmount?: number | null;
  /**
   * Total amount including tax
   */
  total: number;
  /**
   * Date the invoice was created
   */
  invoiceDate: string;
  /**
   * Payment due date
   */
  dueDate: string;
  /**
   * Date the invoice was fully paid
   */
  paidDate?: string | null;
  /**
   * Amount paid (for partial payments)
   */
  paidAmount?: number | null;
  /**
   * Payment terms (copied from client preferences)
   */
  terms?: ('due-on-receipt' | 'net-15' | 'net-30' | 'net-45' | 'net-60') | null;
  /**
   * Customer-facing notes (appears on invoice)
   */
  notes?: string | null;
  /**
   * Internal notes (not visible to customer)
   */
  internalNotes?: string | null;
  quickbooks?: {
    /**
     * QuickBooks Invoice ID
     */
    invoiceId?: string | null;
    syncStatus?: ('not-synced' | 'synced' | 'error') | null;
    /**
     * Last successful sync timestamp
     */
    lastSyncedAt?: string | null;
    /**
     * Error message if sync failed
     */
    syncError?: string | null;
  };
  /**
   * User who approved this invoice
   */
  approvedBy?: (number | null) | User;
  /**
   * When the invoice was approved
   */
  approvedAt?: string | null;
  /**
   * User who created this invoice
   */
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  client: number | Client;
  amount: number;
  paymentDate: string;
  referenceNumber?: string | null;
  source?: ('csv-import' | 'manual') | null;
  status: 'unmatched' | 'matched';
  matchedJob?: (number | null) | Job;
  matchedInvoice?: (number | null) | Invoice;
  notes?: string | null;
  importedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  user: number | User;
  title: string;
  message: string;
  type: 'info' | 'success' | 'warning' | 'error';
  read?: boolean | null;
  /**
   * Link to related job if applicable
   */
  relatedJob?: (number | null) | Job;
  /**
   * URL to navigate to when notification is clicked
   */
  actionUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-templates".
 */
export interface NotificationTemplate {
  id: number;
  /**
   * Internal name for this template
   */
  name: string;
  /**
   * When this notification should be sent
   */
  type:
    | 'scheduled'
    | 'completed'
    | 'delivered'
    | 'scan-completed'
    | 'upload-completed'
    | 'qc-completed'
    | 'transfer-completed'
    | 'floorplan-completed'
    | 'photos-completed'
    | 'asbuilts-completed';
  /**
   * Only active templates will be used
   */
  active?: boolean | null;
  /**
   * Email subject line. Available variables: {{jobNumber}}, {{clientName}}, {{location}}
   */
  subject: string;
  /**
   * Email body. Available variables: {{jobNumber}}, {{clientName}}, {{location}}, {{targetDate}}, {{scannedDate}}, {{uploadLink}}, {{customMessage}}
   */
  body: string;
  /**
   * Use this as the default template for this notification type
   */
  defaultTemplate?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-templates".
 */
export interface JobTemplate {
  id: number;
  /**
   * e.g., "Standard 3D Scan", "Scan + As-Builts + Hosting"
   */
  name: string;
  /**
   * Leave empty for general template, or select client for client-specific template
   */
  client?: (number | null) | Client;
  /**
   * Only active templates appear in job creation
   */
  isActive?: boolean | null;
  defaultWorkflow: number | WorkflowTemplate;
  /**
   * Products will be automatically added to jobs created with this template
   */
  defaultProducts?: (number | Product)[] | null;
  /**
   * Pre-filled instructions (will be combined with client template + product instructions)
   */
  defaultInstructions?: string | null;
  /**
   * Suggested price (user can override)
   */
  defaultPricing?: number | null;
  /**
   * Show warning if these fields are empty (non-blocking)
   */
  requiredFields?: ('captureAddress' | 'city' | 'state' | 'zip' | 'targetDate' | 'sqFt' | 'propertyType')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-messages".
 */
export interface JobMessage {
  id: number;
  /**
   * The job this message belongs to
   */
  job: number | Job;
  /**
   * Who sent this message
   */
  author:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'technicians';
        value: number | Technician;
      };
  message: string;
  /**
   * Type of message for categorization
   */
  messageType: 'message' | 'question' | 'answer' | 'update' | 'issue' | 'qc-feedback';
  attachments?:
    | {
        file: number | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Has this message been read by the recipient
   */
  isRead?: boolean | null;
  /**
   * How this message was sent
   */
  sentVia?: ('app' | 'email' | 'sms') | null;
  /**
   * Whether email notification was sent
   */
  emailSent?: boolean | null;
  /**
   * Whether SMS notification was sent
   */
  smsSent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        id?: string | null;
        title?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'technicians';
        value: number | Technician;
      } | null)
    | ({
        relationTo: 'vendors';
        value: number | Vendor;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'equipment';
        value: number | Equipment;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'notification-templates';
        value: number | NotificationTemplate;
      } | null)
    | ({
        relationTo: 'workflow-templates';
        value: number | WorkflowTemplate;
      } | null)
    | ({
        relationTo: 'job-templates';
        value: number | JobTemplate;
      } | null)
    | ({
        relationTo: 'job-messages';
        value: number | JobMessage;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  content?: T;
  author?:
    | T
    | {
        name?: T;
        email?: T;
      };
  post?: T;
  isApproved?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  primaryContact?: T;
  clientType?: T;
  billingPreference?: T;
  email?: T;
  phone?: T;
  companyName?: T;
  billingAddress?: T;
  notes?: T;
  instructionTemplate?: T;
  accountManager?: T;
  defaultWorkflow?: T;
  invoicingPreferences?:
    | T
    | {
        terms?: T;
        batchDay?: T;
        invoiceNotes?: T;
        autoApprove?: T;
        taxExempt?: T;
        taxRate?: T;
        taxJurisdiction?: T;
      };
  integrations?:
    | T
    | {
        quickbooks?:
          | T
          | {
              customerId?: T;
              syncStatus?: T;
              lastSyncedAt?: T;
              syncError?: T;
            };
        hubspot?:
          | T
          | {
              contactId?: T;
              syncStatus?: T;
              lastSyncedAt?: T;
              syncError?: T;
            };
      };
  notificationPreferences?:
    | T
    | {
        enableNotifications?: T;
        notificationEmail?: T;
        notificationPhone?: T;
        notifyOnScheduled?: T;
        notifyOnCompleted?: T;
        notifyOnDelivered?: T;
        notifyOnScanCompleted?: T;
        notifyOnUploadCompleted?: T;
        notifyOnQcCompleted?: T;
        notifyOnTransferCompleted?: T;
        notifyOnFloorplanCompleted?: T;
        notifyOnPhotosCompleted?: T;
        notifyOnAsbuiltsCompleted?: T;
        customMessage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technicians_select".
 */
export interface TechniciansSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  user?: T;
  type?: T;
  vendor?: T;
  baseCommissionRate?: T;
  phone?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors_select".
 */
export interface VendorsSelect<T extends boolean = true> {
  companyName?: T;
  contactPerson?: T;
  billingEmail?: T;
  billingPhone?: T;
  taxID?: T;
  paymentTerms?: T;
  notes?: T;
  active?: T;
  integrations?:
    | T
    | {
        quickbooks?:
          | T
          | {
              vendorId?: T;
              syncStatus?: T;
              lastSyncedAt?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  unitType?: T;
  basePrice?: T;
  isRecurring?: T;
  requiresVendor?: T;
  description?: T;
  defaultInstructions?: T;
  taxable?: T;
  hasDefaultExpense?: T;
  defaultExpenseCost?: T;
  expenseDescription?: T;
  excludeFromCalendar?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment_select".
 */
export interface EquipmentSelect<T extends boolean = true> {
  label?: T;
  assetId?: T;
  type?: T;
  lastCalibrationDate?: T;
  nextMaintenanceDue?: T;
  assignedTo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  jobId?: T;
  modelName?: T;
  priority?: T;
  status?: T;
  invoiceStatus?: T;
  invoice?: T;
  invoicedAt?: T;
  client?: T;
  endClientName?: T;
  endClientCompany?: T;
  tech?: T;
  sitePOCName?: T;
  sitePOCPhone?: T;
  sitePOCEmail?: T;
  captureAddress?: T;
  city?: T;
  state?: T;
  zip?: T;
  sqFt?: T;
  estimatedDuration?: T;
  propertyType?: T;
  schedulingNotes?: T;
  region?: T;
  captureType?: T;
  equipment?: T;
  purposeOfScan?: T;
  techInstructions?: T;
  lineItems?:
    | T
    | {
        product?: T;
        quantity?: T;
        instructions?: T;
        excludeFromCalendar?: T;
        id?: T;
      };
  customTodoItems?:
    | T
    | {
        task?: T;
        notes?: T;
        id?: T;
      };
  targetDate?: T;
  timezone?: T;
  scannedDate?: T;
  googleCalendarEventId?: T;
  uploadLink?: T;
  mediaUploadLink?: T;
  gasExpense?: T;
  isOutsourced?: T;
  vendorPrice?: T;
  travelPayout?: T;
  offHoursPayout?: T;
  commissionPayoutDate?: T;
  commissionPaymentStatus?: T;
  commissionPaidAt?: T;
  workflowTemplate?: T;
  workflowSteps?:
    | T
    | {
        stepName?: T;
        completed?: T;
        completedAt?: T;
        completedBy?: T;
        notes?: T;
        id?: T;
      };
  qcChecklist?:
    | T
    | {
        accuracyOk?: T;
        coverageOk?: T;
        fileNamingOk?: T;
      };
  qcStatus?: T;
  qcAssignedTo?: T;
  qcNotes?: T;
  qcStartTime?: T;
  qcEndTime?: T;
  revisionRequests?:
    | T
    | {
        requestedBy?: T;
        requestedAt?: T;
        description?: T;
        resolved?: T;
        resolvedAt?: T;
        id?: T;
      };
  totalPrice?: T;
  vendorCost?: T;
  margin?: T;
  externalExpenses?:
    | T
    | {
        description?: T;
        supplier?: T;
        contactInfo?: T;
        amount?: T;
        paymentStatus?: T;
        paidDate?: T;
        notes?: T;
        autoGenerated?: T;
        quickbooksId?: T;
        quickbooksDocNumber?: T;
        quickbooksSyncedAt?: T;
        id?: T;
      };
  subcontractorVendor?: T;
  subcontractorInvoiceAttachment?: T;
  subInvoiceData?: T;
  subInvoiceImported?: T;
  discount?:
    | T
    | {
        type?: T;
        value?: T;
        amount?: T;
      };
  subtotal?: T;
  taxAmount?: T;
  totalWithTax?: T;
  completionToken?: T;
  deliverables?:
    | T
    | {
        model3dLink?: T;
        floorPlansLink?: T;
        photosVideosLink?: T;
        asBuiltsLink?: T;
        otherAssetsLink?: T;
        deliveryNotes?: T;
        deliveredDate?: T;
      };
  messageToken?: T;
  schedulingRequest?:
    | T
    | {
        requestType?: T;
        sentAt?: T;
        deadline?: T;
        reminderSent?: T;
        reminderSentAt?: T;
        timeOptions?:
          | T
          | {
              optionNumber?: T;
              date?: T;
              timeWindow?: T;
              startTime?: T;
              endTime?: T;
              specificTime?: T;
              id?: T;
            };
        requestMessage?: T;
        specialInstructions?: T;
      };
  techResponse?:
    | T
    | {
        respondedAt?: T;
        interested?: T;
        selectedOption?: T;
        preferredStartTime?: T;
        proposedOptions?:
          | T
          | {
              date?: T;
              startTime?: T;
              notes?: T;
              id?: T;
            };
        declineReason?: T;
        notes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  invoiceNumber?: T;
  status?: T;
  client?: T;
  jobs?: T;
  lineItems?:
    | T
    | {
        description?: T;
        quantity?: T;
        rate?: T;
        amount?: T;
        taxable?: T;
        jobReference?: T;
        id?: T;
      };
  subtotal?: T;
  taxRate?: T;
  taxAmount?: T;
  total?: T;
  invoiceDate?: T;
  dueDate?: T;
  paidDate?: T;
  paidAmount?: T;
  terms?: T;
  notes?: T;
  internalNotes?: T;
  quickbooks?:
    | T
    | {
        invoiceId?: T;
        syncStatus?: T;
        lastSyncedAt?: T;
        syncError?: T;
      };
  approvedBy?: T;
  approvedAt?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  client?: T;
  amount?: T;
  paymentDate?: T;
  referenceNumber?: T;
  source?: T;
  status?: T;
  matchedJob?: T;
  matchedInvoice?: T;
  notes?: T;
  importedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  title?: T;
  message?: T;
  type?: T;
  read?: T;
  relatedJob?: T;
  actionUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-templates_select".
 */
export interface NotificationTemplatesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  active?: T;
  subject?: T;
  body?: T;
  defaultTemplate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-templates_select".
 */
export interface WorkflowTemplatesSelect<T extends boolean = true> {
  name?: T;
  jobType?: T;
  isActive?: T;
  description?: T;
  steps?:
    | T
    | {
        name?: T;
        description?: T;
        order?: T;
        statusMapping?: T;
        requiredRole?: T;
        actionLabel?: T;
        requiresDeliverables?: T;
        triggers?:
          | T
          | {
              sendNotification?: T;
              notificationRecipients?: T;
              notificationMessage?: T;
              sendClientEmail?: T;
              emailTemplate?: T;
              createInvoice?: T;
              createRecurringInvoice?: T;
              recurringInvoiceDelay?: T;
              recurringInvoiceAmount?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-templates_select".
 */
export interface JobTemplatesSelect<T extends boolean = true> {
  name?: T;
  client?: T;
  isActive?: T;
  defaultWorkflow?: T;
  defaultProducts?: T;
  defaultInstructions?: T;
  defaultPricing?: T;
  requiredFields?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-messages_select".
 */
export interface JobMessagesSelect<T extends boolean = true> {
  job?: T;
  author?: T;
  message?: T;
  messageType?: T;
  attachments?:
    | T
    | {
        file?: T;
        description?: T;
        id?: T;
      };
  isRead?: T;
  sentVia?: T;
  emailSent?: T;
  smsSent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        id?: T;
        title?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}